// <auto-generated />
using System;
using MQTT_DataLogger.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MQTT_DataLogger.Migrations
{
    [DbContext(typeof(MQTTDbContext))]
    [Migration("20210622230035_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("MQTT_DataLogger.Data.Measurement", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<double>("CPUTemp")
                        .HasColumnType("float");

                    b.Property<double>("CPUUsage")
                        .HasColumnType("float");

                    b.Property<string>("DeviceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("GPUTemp")
                        .HasColumnType("float");

                    b.Property<double>("GPUUsage")
                        .HasColumnType("float");

                    b.Property<double>("RAMUsage")
                        .HasColumnType("float");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Measurements");
                });
#pragma warning restore 612, 618
        }
    }
}
